title: "Elaine Astrand"
name: "Elaine Astrand"
email: ""
description: "Associate Professor"
repository: "elainea/eastrand.github.io"

remote_theme: "mmistakes/minimal-mistakes@latest"

minimal_mistakes_skin: "default"   # choose: air, contrast, dark, mint, neon, solarized, etc.

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-include-cache

include:
  - _pages

# Navigation (linked to _data/navigation.yml)
collections:
  posts:
    output: true

defaults:
  # pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

  # homepage
  - scope:
      path: ""
      type: index
    values:
      layout: splash
